# Generated by Django 3.0 on 2019-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emousic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
