# Generated by Django 3.0 on 2019-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('emousic', '0002_track_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='track',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
