#senticnote['concept_name'] = ['pleasantness_value', 'attention_value', 'sensitivity_value', 'aptitude_value', 'primary_mood', 'secondary_mood', 'polarity_label', 'polarity_value', 'semantics1', 'semantics2', 'semantics3', 'semantics4', 'semantics5']
senticnote = {}
senticnote['round'] = ['disgust', 'boredom', 'sadness', 'fear', 'potency', 'tenderness']
senticnote['sharp'] = ['serenity', 'joy', 'surprise', 'activity', 'anger']
senticnote['staccato'] = ['anger', 'fear']
senticnote['legato'] = ['tenderness', 'sadness']
senticnote['consonant'] = ['relaxation', 'tenderness']
senticnote['dissonant'] = ['anger', 'tension', 'fear']
senticnote['soft'] = ['fear', 'sadness', 'tenderness'] # 0-42
senticnote['loud'] = ['anger'] # 85-127
senticnote['large'] = ['fear']
senticnote['small'] = ['joy', 'serenity', 'activity']
senticnote['wide'] = ['fear']
senticnote['narrow'] = ['sadness']
senticnote['major'] = ['joy']
senticnote['minor'] = ['sadness', 'disgust', 'anger']
senticnote['high'] = ['surprise', 'potency', 'anger', 'fear', 'activity']
senticnote['low'] = ['boredom', 'serenity', 'sadness']
senticnote['slow'] = ['sadness', 'boredom', 'disgust', 'tenderness'] # 0-120
senticnote['fast'] = ['activity', 'surprise', 'joy', 'serenity', 'potency', 'anger', 'fear'] # 120-200+
